### ISSUE TITLE
Insufficient dependencies pulled in for Gnome on Ubuntu 18.04

### ISSUE THREAD

**Issue by ColonelPanicks** [openflighthpc/flight-desktop#19]
## Background

On a fresh Ubuntu Server installation, preparing a Gnome desktop with:
```
sudo /opt/flight/bin/flight desktop prepare gnome
```

Does not provide adequate dependencies for some of the desktop applications (e.g. Byobu Terminal - this requires Xterm in order to function). 

After installing the `xterm` desktop type with:
```
sudo /opt/flight/bin/flight desktop prepare xterm
```

There are still issues with symbols not correctly rendering within the terminal

## Solution

The following command provided sufficient dependencies

```
sudo apt-get install ubuntu-desktop
```

**Comment by mjtko** [comment]
Closed via https://github.com/openflighthpc/flight-desktop-types/commit/23598a90cbe640c2da36943db9bb7eb37f02833a and https://github.com/openflighthpc/flight-desktop/commit/3dfabef8baa8e2334dae6aa3a3b7e1c8e5c40cea
