### ISSUE TITLE
OpenFlight Background Not Set (Gnome - Ubuntu 18.04)

### ISSUE THREAD

**Issue by ColonelPanicks** [openflighthpc/flight-desktop#20]
As stated, when launching a Gnome desktop on Ubuntu 18.04 (after the fixes in #19 ) the default Ubuntu background is shown, this should be the OpenFlight desktop background.

**Comment by mjtko** [comment]
I'm not seeing this in the latest versions of flight-desktop/flight-desktop-types:

![Screenshot 2020-06-26 at 17 34 25](https://user-images.githubusercontent.com/206834/85880115-634a0800-b7d3-11ea-9521-6993960c3551.png)

There have been a few changes in the recent RCs that might explain why it's started working -- can you retest and close if it's working for you now please?

**Comment by ColonelPanicks** [comment]
Have retested, this seems to have been addressed. Thanks Mark!
