### ISSUE TITLE
Profile Not Sourced in Desktop Environments (Ubuntu 18.04)

### ISSUE THREAD

**Issue by ColonelPanicks** [openflighthpc/flight-desktop#21]
After launching a Gnome desktop environment (with fixes from #19 ) I am unable to run the flight commands in a terminal. It seems that the profile is not sourced.

It is possible to expose the flight command to a terminal in a VNC session by running `source /etc/profile`.

**Comment by ColonelPanicks** [comment]
Note: This issue is definitely not present when launching an xterm session. It seems that the problem may lay closer to the Ubuntu/Gnome side of things.

**Comment by ColonelPanicks** [comment]
Strangely enough, launching an xterm terminal in Gnome does *not* load the profile

**Comment by mjtko** [comment]
I spotted that the `terminal` session type explicitly requests a login shell for `xterm` via:

```
xterm ...
    -xrm 'xterm*loginShell: true' \
```

The `xterm` session type doesn't tho. Were you testing with the `terminal` or `xterm` type?

Getting a handle on what happens for non-login shells is the root of this issue -- needs to be as intuitive as possible. Currently the behaviour varies between Ubuntu and CentOS.

In CentOS both login shells (via `/etc/profile`) and interactive shells (via `/etc/bashrc`) source `/etc/profile.d` scripts, so Just Work :tm: in both cases.

In Ubuntu:

1. Login shells source `/etc/profile.d` scripts (via `/etc/profile`), so Just Work :tm:
2. Interactive (but not login shells) don't source profile stuff (they source `/etc/bash.bashrc`). This is where we need to consider what to do.

It's tricky tho, cos it may be unexpected to Ubuntu users for interactive shell behaviour to change.

🤔

**Comment by ColonelPanicks** [comment]
To confirm, it was the xterm session type, not the terminal one.

Thank you for clarifying the differences between Ubuntu and CentOS with interactive logins. This is quite frustrating to see a fairly big difference between the 2 and I definitely agree that we shouldn't be modifying how Ubuntu behaves to fit our needs.

A [quick look online](https://unix.stackexchange.com/a/122430/210036) suggests that maybe the file `~/.xprofile` is likely to be respected by multiple display managers. I'll continue poking at my instance to see if I can find somewhere that seems appropriate for putting this stuff (afaics `/etc/bash.bashrc` doesn't source any directory files in the same way as `/etc/profile` so not like there's someone else we can just plop the scripts in...)

**Comment by ColonelPanicks** [comment]
The linked Omnibus issue will introduce a change that will allow the `flight` command to be exposed, however *the `flight start` command is needed in every terminal session within the session*, regardless of if `flight set always on` has been run. According to @mjtko this has something to do with the `flight_ACTIVE` environment variable.
